DROP DATABASE IF EXISTS j65x82iikc4ztpsw;
CREATE DATABASE j65x82iikc4ztpsw;
USE j65x82iikc4ztpsw;

CREATE TABLE burgers (
    id INTEGER(11) AUTO_INCREMENT NOT NULL,
    burger_name VARCHAR(50) NOT NULL,
    devoured BOOLEAN NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);